import { NextResponse } from 'next/server';
import { generateText } from 'ai';
import { createAnthropic } from '@ai-sdk/anthropic';

// Allow responses up to 60 seconds
export const maxDuration = 60;

const tryParseJson = (raw: string): any | null => {
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
};

const parseModelResponse = (text: string): any | null => {
  const trimmed = text.trim();
  if (!trimmed) return null;

  const parseCandidates = new Set<string>([trimmed]);

  const fencedJsonMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fencedJsonMatch?.[1]) {
    parseCandidates.add(fencedJsonMatch[1].trim());
  }

  const firstObjectStart = trimmed.indexOf('{');
  const lastObjectEnd = trimmed.lastIndexOf('}');
  if (firstObjectStart !== -1 && lastObjectEnd > firstObjectStart) {
    parseCandidates.add(trimmed.slice(firstObjectStart, lastObjectEnd + 1));
  }

  for (const candidate of parseCandidates) {
    const parsed = tryParseJson(candidate);
    if (parsed && typeof parsed === 'object') return parsed;
  }

  return null;
};

export async function POST(req: Request) {
  try {
    const { playerA, playerB } = await req.json();

    if (!playerA || !playerB) {
      return NextResponse.json({ error: 'Missing player data' }, { status: 400 });
    }

    const trimPlayer = (p: any) => {
        return {
            name: p.fullName,
            checkIns: p.checkInCount,
            avgProgress: p.avgParticipantPercent ?? p.avgObjectiveProgress,
            topObjectives: p.topObjectives.map((obj: any) => ({
                name: obj.objectiveName,
                progress: obj.progress,
                tasks:
                  obj.actualDetails
                    ?.map((detail: any) => {
                      const detailProgress = Math.round(detail?.progress || 0);
                      const krList =
                        detail?.details
                          ?.map((kr: any) => `${kr.krTitle} (${Math.round(kr.krProgress || 0)}%)`)
                          .join(', ') || 'no KR';
                      return `${detail?.title || 'Objective detail'} [${detailProgress}%]: ${krList}`;
                    })
                    .join(' | ') || 'No specific breakdown',
            }))
        };
    };

    const dataA = trimPlayer(playerA);
    const dataB = trimPlayer(playerB);

    const apiKey = process.env.ANTHROPIC_API_KEY || process.env.NEXT_PUBLIC_ANTHROPIC_API_KEY;
    const maxRounds = Math.max(dataA.topObjectives.length, dataB.topObjectives.length);

    if (!apiKey) {
      return NextResponse.json(
        {
          error: 'AI_UNAVAILABLE',
          message:
            'Anthropic API key is not configured. Set ANTHROPIC_API_KEY (or NEXT_PUBLIC_ANTHROPIC_API_KEY) so eval copy is generated by the model only.',
        },
        { status: 503 },
      );
    }

    const calcScore = (p: any): number => {
        let score = p.avgProgress || 0;
        score += (p.checkIns || 0) * 1.5; 
        score += (p.topObjectives.length > 1 ? (p.topObjectives.length * 2) : 0);
        return Math.max(0, Math.round(score));
    };

    let p1Score = calcScore(dataA);
    let p2Score = calcScore(dataB);

    if (p1Score === p2Score) {
        if (dataA.checkIns > dataB.checkIns) p1Score++;
        else if (dataB.checkIns > dataA.checkIns) p2Score++;
        else p1Score++;
    }
    
    const exactWinner = p1Score > p2Score ? dataA.name : dataB.name;

    const matchedRounds = Array.from({ length: maxRounds }).map((_, i) => ({
        roundNumber: i + 1,
        p1Data: dataA.topObjectives[i] ? `${dataA.topObjectives[i].name} (Tasks: ${dataA.topObjectives[i].tasks})` : "NO OBJECTIVE (ว่างเปล่า)",
        p2Data: dataB.topObjectives[i] ? `${dataB.topObjectives[i].name} (Tasks: ${dataB.topObjectives[i].tasks})` : "NO OBJECTIVE (ว่างเปล่า)",
    }));

    const schemaExampleRounds = Array.from({ length: maxRounds }).map((_, i) => ({
       roundNumber: i + 1,
       p1_badge: `Badge for P1's obj in Thai`,
       p2_badge: `Badge for P2's obj in Thai`,
       commentary: `Thai commentary for round ${i + 1}.`
    }));

    const prompt = `You are a witty staff+ engineer doing a dry OKR "eval pass" — like reviewing two PRs of someone's quarter. Tone: playful dev humor (latency, APIs, deploys, p99, caching) but grounded in the OKR tasks below. NOT e-sports or fighting game commentary.

The math is FIXED. You MUST use these EXACT scores and winner:
Player 1 (${dataA.name}) Final Score: ${p1Score}
Player 2 (${dataB.name}) Final Score: ${p2Score}
Winner: ${exactWinner}

This is OBJECTIVE-BY-OBJECTIVE. You MUST create EXACTLY ${maxRounds} rounds in your JSON array.
Use the pre-matched round data. If a player has "NO OBJECTIVE (ว่างเปล่า)", tease them lightly in engineer voice (empty queue / no tickets).
For each round, p1_badge and p2_badge MUST be short (max ~8 words), Thai or Thai+English, funny "tuning" vibes — e.g. self-deprecating ship culture, NOT violent metaphors.
DO NOT MIX UP PLAYER 1 AND PLAYER 2.

Pre-Matched Rounds Data:
${JSON.stringify(matchedRounds, null, 2)}

Respond with a JSON object EXACTLY in this format:
{
  "winner": "${exactWinner}",
  "scoreA": ${p1Score},
  "scoreB": ${p2Score},
  "intro_hype": "Short Thai intro to this OKR comparison; optional one emoji max.",
  "rounds": ${JSON.stringify(schemaExampleRounds, null, 4)},
  "playerA_strengths_weaknesses": "Short Thai paragraph: strengths/risks for Player A from OKR angle.",
  "playerB_strengths_weaknesses": "Short Thai paragraph: strengths/risks for Player B from OKR angle.",
  "conclusion": "Thai: why the winner scored higher in plain OKR terms (progress, breadth, consistency)."
}

Return ONLY raw JSON, no code fences, no extra text.`;

    const anthropic = createAnthropic({ apiKey: apiKey });
    const { text } = await generateText({
        model: anthropic('claude-3-haiku-20240307'),
        prompt: prompt,
    });

    const parsed = parseModelResponse(text);
    
    if (parsed) {
        if (!Array.isArray(parsed.rounds)) parsed.rounds = [];
        
        // Safety for missing keys
        parsed.playerA_strengths_weaknesses =
          typeof parsed.playerA_strengths_weaknesses === 'string'
            ? parsed.playerA_strengths_weaknesses
            : '';
        parsed.playerB_strengths_weaknesses =
          typeof parsed.playerB_strengths_weaknesses === 'string'
            ? parsed.playerB_strengths_weaknesses
            : '';

        return NextResponse.json(parsed);
    }

    return NextResponse.json({ error: 'Data parsing failed at AI level' }, { status: 500 });
  } catch (error) {
    console.error('Error generating AI comparison:', error);
    return NextResponse.json(
      { error: 'Failed to generate AI comparison' },
      { status: 500 }
    );
  }
}


